### ISSUE TITLE
Different user_id on different sites

### ISSUE THREAD

**Issue by sopoforic** [karlicoss/stexport#5]
In my exports, I get data for different users for each site--whichever user has the ID number passed to stexport. The problem is that the user_id for the same user differs per-site.

It seems to me that it is necessary, rather, to use the [/me endpoint](https://api.stackexchange.com/docs/me) on each site to get the correct user_id. Am I misunderstanding how to use stexport?

**Comment by karlicoss** [comment]
Hi @sopoforic you're completely right, thanks! This is a great catch.
I never noticed because I've only using stackoverflow data so far :see_no_evil:

**Comment by sopoforic** [comment]
Confirmed, this fixes the issue. Thanks!
